from damply import dirs as dmpdirs

# could alternatively pass this in the CLI via `--configfile $CONFIG/config.yaml`
# configfile: dmpdirs.CONFIG / "datasets" / "NSCLC-Radiomics_test.yaml"

COMBINED_DATA_NAME = config["DATA_SOURCE"] + "_" + config["DATASET_NAME"]

include: "scripts/mit/run_mit.smk"

rule run_mit:
    # Target rule - coordinates MIT processing workflow
    input:
        mit_autopipeline_index=dmpdirs.PROCDATA / COMBINED_DATA_NAME / "images" / f"mit_{config["DATASET_NAME"]}" / f"mit_{config["DATASET_NAME"]}_index.csv",
        mit_niftis_directory=dmpdirs.PROCDATA / COMBINED_DATA_NAME / "images" / f"mit_{config["DATASET_NAME"]}"
